# Generated by Django 5.2.6 on 2025-10-04 10:58

import dashboard_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=dashboard_app.models.foto_aluno_path)),
            ],
            options={
                'db_table': 'aluno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreaDoConhecimento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'Área do Conhecimento',
                'verbose_name_plural': 'Áreas do Conhecimento',
                'db_table': 'area_do_conhecimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=15, unique=True)),
                ('descricao', models.CharField(max_length=45, unique=True)),
                ('horas', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'disciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'serie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
                ('descricao', models.CharField(max_length=45)),
                ('turma_id', models.CharField(blank=True, max_length=3, null=True)),
                ('turma_ano', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'turma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'turno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlunoTurma',
            fields=[
                ('aluno_matricula', models.OneToOneField(db_column='aluno_matricula', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard_app.aluno')),
                ('turma_id', models.CharField(max_length=3)),
                ('turma_ano', models.IntegerField()),
            ],
            options={
                'db_table': 'aluno_turma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boletim',
            fields=[
                ('aluno_matricula', models.OneToOneField(db_column='aluno_matricula', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard_app.aluno')),
                ('turma_id', models.CharField(max_length=3)),
                ('turma_ano', models.IntegerField()),
                ('bimestre1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('bimestre2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('recusem1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('bimestre3', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('bimestre4', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('recusem2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('recfinal', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('faltas', models.IntegerField(blank=True, null=True)),
                ('faltaspercent', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'boletim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlunoFoto',
            fields=[
            ],
            options={
                'verbose_name': 'Foto de Aluno',
                'verbose_name_plural': 'Fotos de Alunos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dashboard_app.aluno',),
        ),
        migrations.CreateModel(
            name='DisciplinaCursoSerie',
            fields=[
                ('disciplina', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard_app.disciplina')),
            ],
            options={
                'db_table': 'disciplina_curso_serie',
                'managed': False,
            },
        ),
    ]
